nylas_sample/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("nylasapp.urls"))
]

nylasapp/urls.py
from django.urls import path
from .views import read_emails, handle_authorization, start_authorization, micro_start_authorization, \
    yahoo_start_authorization, send_email, all_nylas_accounts, retry_authorization

urlpatterns = [
    path('read-emails/', read_emails, name='read_emails'),
    path('start-authorization/', start_authorization, name='start_authorization'),
    path('micro-authorization/', micro_start_authorization, name='micro_start_authorization'),
    path('yahoo-authorization/', yahoo_start_authorization, name='yahoo_start_authorization'),
    path('handle-authorization/', handle_authorization, name='handle_authorization'),
    path('send_email/', send_email, name='send_email'),
    path('', all_nylas_accounts, name='all_nylas_accounts'),
    path('retry-authorization/', retry_authorization, name='retry_authorization'),

]

nylasapp/forms.py
from django import forms

from nylasapp.models import UserAccount


class UserAccountForm(forms.Form):
    user_account = forms.ModelChoiceField(
        queryset=UserAccount.objects.all(),
        empty_label=None,
        to_field_name='email_address',
        label='Select User Account'
    )

templates/all_nylas_accounts.html
<!-- all_nylas_accounts.html -->
<!DOCTYPE html>
<html>
<head>
    <title>All Nylas Accounts</title>
              <style>
        .button {
            display: inline-block;
            padding: 10px 20px;
            font-size: 16px;
            text-align: center;
            text-decoration: none;
            background-color: #4CAF50;
            color: white;
            border: 2px solid #4CAF50;
            border-radius: 5px;
            cursor: pointer;
        }
        .cbg{
             background-color: #177ff3;
        }
        .cbr{
 background-color: #ec400d;
        }

        .button:hover {
            background-color: white;
            color: #4CAF50;
        }
        table td{
            padding: 10px;
            text-align: center;
        }

    </style>
</head>
<body>
<h1>
    My Nylas Accounts
</h1>
<hr>

<p>
    <a class="button" href="{% url 'send_email' %}">Send Mail</a> &nbsp;
    <a class="button" href="{% url 'read_emails' %}">Read Mail</a> &nbsp;
    <a class="button" href="{% url 'all_nylas_accounts' %}">All Accounts</a> &nbsp;
    <a class="button cbg" href="{% url 'start_authorization' %}">Add Account</a> &nbsp;

</p><hr>
<br>
    <table border="1" style="width: 100%">
        <thead>
            <tr>
                <th>Account ID</th>
                <th>Email Address</th>
                <th>billing_state</th>
                <th>provider</th>
                <th>sync_state</th>
                                <th>Delete</th>
{#                <th>Retry Sync</th>#}
                <th>ReLogin</th>

            </tr>
        </thead>
        <tbody>
{#        {{ account_data }}#}
            {% for account in account_data %}
                <tr>
                    <td>{{ account.id }}</td>
                    <td>{{ account.email_address }}</td>
                    <td>{{ account.billing_state }}</td>
                    <td>{{ account.provider }}</td>
                    <td>{{ account.sync_state }}</td>
                  <td>
                        <form method="post" action="{% url 'all_nylas_accounts' %}">
                            {% csrf_token %}
                            <input type="hidden" name="delete_account_id" value="{{ account.id }}">
                            <button class="button cbr" type="submit">Delete</button>
                        </form>
                    </td>
{#                <td>#}
{#                        <form method="post" action="{% url 'all_nylas_accounts' %}">#}
{#                            {% csrf_token %}#}
{#                            <input type="hidden" name="retry_sync_account_id" value="{{ account.id }}">#}
{#                            <button class="button cbg" type="submit">Retry Sync</button>#}
{#                        </form>#}
{#                    </td>#}
                <td>
<a class="button" href="{% url 'retry_authorization' %}?email={{ account.email_address }}">Retry Authorization</a>

                </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

templates/my_messages.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
          <style>
        .button {
            display: inline-block;
            padding: 10px 20px;
            font-size: 16px;
            text-align: center;
            text-decoration: none;
            background-color: #4CAF50;
            color: white;
            border: 2px solid #4CAF50;
            border-radius: 5px;
            cursor: pointer;
        }
        .cbg{
             background-color: #177ff3;
        }
        .cbr{
 background-color: #ec400d;
        }

        .button:hover {
            background-color: white;
            color: #4CAF50;
        }
        table td{
            padding: 10px;
            text-align: center;
        }

    </style>
</head>
<body>
<h1>
    My Nylas Mails
</h1>
<hr>
<form method="post">
  {% csrf_token %}
{{ form.as_p }}
  <input class="button" type="submit" value="Submit">
</form>
{%  if errors %}
<p style="color: red;font-weight: bold">{{ errors }}</p>
{% endif %}

<p>
    <a class="button" href="{% url 'send_email' %}">Send Mail</a> &nbsp;
    <a class="button" href="{% url 'read_emails' %}">Read Mail</a> &nbsp;
    <a class="button" href="{% url 'all_nylas_accounts' %}">All Accounts</a> &nbsp;
    <a class="button cbg" href="{% url 'start_authorization' %}">Add Account</a> &nbsp;

</p><hr>
{#<P>{{ email_list }}</P>#}
<table border="1" style="width: 100%">
    <thead>
        <tr>
            <th>No</th>
            <th>Date</th>
            <th>Subject</th>
            <th>From</th>
            <th>Unread</th>
            <th>Label</th>

        </tr>
    </thead>
    <tbody>
        {% for email in email_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ email.date }}</td>
                <td>{{ email.subject }}
                    <br>
                    {{ email.id}}
                </td>
                <td>
{% for email in email.from_mail %}
    EMail : {{ email.email }} <br>
    Name : {{ email.name }}
    {% endfor %}
                </td>
                <td>{{ email.unread }}</td>
                <td>
                    {% for label in email.labels %}
                        {{ label.display_name }} -
                        {% endfor %}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{{ threads }}
</body>
</html>

templates/send_email.html
<!DOCTYPE html>
<html>
<head>
    <title>Nylas Send Email</title>
      <style>
        .button {
            display: inline-block;
            padding: 10px 20px;
            font-size: 16px;
            text-align: center;
            text-decoration: none;
            background-color: #4CAF50;
            color: white;
            border: 2px solid #4CAF50;
            border-radius: 5px;
            cursor: pointer;
        }
        .cbg{
             background-color: #177ff3;
        }
        .cbr{
 background-color: #ec400d;
        }

        .button:hover {
            background-color: white;
            color: #4CAF50;
        }
        table td{
            padding: 10px;
            text-align: center;
        }

    </style>
</head>

<body>
<h1>
    My Nylas Mails
</h1>
<hr>

<p>
    <a class="button" href="{% url 'send_email' %}">Send Mail</a> &nbsp;
    <a class="button" href="{% url 'read_emails' %}">Read Mail</a> &nbsp;
    <a class="button" href="{% url 'all_nylas_accounts' %}">All Accounts</a> &nbsp;
    <a class="button cbg" href="{% url 'start_authorization' %}">Add Account</a> &nbsp;


</p>
<hr>
{#<form method="post">#}
{#  {% csrf_token %}#}
{#  {{ userform.as_p }}#}
{#</form>#}
    <form method="post" >
        {% csrf_token %}
        <p>
    <label for="id_user_account">Select User Account:</label>
    <select name="user_account" id="id_user_account">
        {% for each in user_accounts %}
  <option value={{ each.email_address }}>{{ each.email_address}}</option>
        {% endfor %}

</select>




  </p>
        <label for="to_email">To Email:</label>
        <input type="email" id="to_email" name="to_email" required><br>
<br
        <label for="subject">Subject:</label>
        <input type="text" id="subject" name="subject" required><br>
<br>
        <label for="body">Body:</label>
        <textarea id="body" name="body" required></textarea><br>
<br>
{#        <button type="submit">Send Email</button>#}
          <input class="button" type="submit" value="Submit">

    </form>

    {% if message %}
        <p style="font-weight: bold;color: blue">{{ message }}</p>
    {% endif %}
</body>
</html>